# Generated by Django 5.0.1 on 2024-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
